### ISSUE TITLE
The error occurred when I ran revolver_jackknife

### ISSUE THREAD

**Issue by ybta2957e** [caravagnalab/revolver#42]
Hello,
I ran the revolver_jackknife and found the errors as shown as pictures.
![image](https://user-images.githubusercontent.com/60736407/151083214-2409aa4f-b489-4833-849d-fd22944ab7d5.png)
Is there any way to handle this error? Thank you for your help.

Best, 
Toby

**Comment by caravagn** [comment]
Hi @ybta2957e, the `easypar` package handles errors for you. 

So here 43 runs were raising the errors and you should run it without paralleling routines - see [easypar](https://caravagn.github.io/easypar/articles/easypar.html#runtime-control-of-easypar) - debug. Errors might come for a variety of reasons, for instance bootstrapping subcohorts with no drivers etc. Errors might just mean, for instance, that you cannnot reconstruct models (which is different from a coding error); so anything raising a `stop(..)` is an error in this sense.
 
In practice this means that you have only 43 effective bootstrap samples. If you wanna get 100, for instance, you could set `resamples = 200` and see how many effective you get. 

BTW the model still makes the jackknife plots with the effective resamples no?

**Comment by ybta2957e** [comment]
Hi @caravagn, 
Thank you for the solution of easypar. I turned off the paralleling routines and got some warnings like these.

Here are warning messages.
![image](https://user-images.githubusercontent.com/60736407/151709715-5151b229-3968-4f90-a665-d9d3aedd20c8.png)

I also found that my minimun group size is 5, but the output message showed that `Minimum group size 2` 
![image](https://user-images.githubusercontent.com/60736407/151688324-e83e4635-6759-4417-a69e-c708c5ce3781.png)
![image](https://user-images.githubusercontent.com/60736407/151688371-ef96c3a6-3411-437e-b67c-8d2fab8109dd.png)

86/200 = 0.43; 114/200 = 0.57
plot_jackknife_coclustering
![image](https://user-images.githubusercontent.com/60736407/151709818-2c52b024-a515-4cf1-b69c-dc48df20d151.png)

plot_jackknife_trajectories_stability
![image](https://user-images.githubusercontent.com/60736407/151709851-9183958e-81ca-4f88-8eb1-6ba7f58b8a96.png)

**Comment by ybta2957e** [comment]
Hi @caravagn,
The effective samples may be used as the denominator for calculating the co-clustering probability and probability_resample.


Best,
Toby
