### ISSUE TITLE
How to prepare input data for revolver/mobster?

### ISSUE THREAD

**Issue by arshah18** [caravagnalab/revolver#43]
Hi Giulio,
Thank you for the great tools [revolver and mobster]!
I have a basic question, I have a patient-pdx data, with  2-4 passages. I got clusters for each case using pyclone-vi. I am wondering how did you derive the data in col[CCF] = R1:1;R2:1;R3:1;R4:1;R5:1;R6:1; finding --> col[is.clonal] = TRUE/FALSE; col[is.driver] = TRUE/FALSE.
I am interested in finding sub-clones and evolutionary tree based on expansion pattern of clonal dynamics.
I have attached the template file of my data.
Thank you!
Rauf
[case1_pycloneResults.xlsx](https://github.com/caravagnalab/revolver/files/8429992/case1_pycloneResults.xlsx)

**Comment by caravagn** [comment]
Hi @arshah18 

Thanks for your message. `is.clonal` should be set to `TRUE` only for the actual clonal cluster estimated by PyClone-VI, that is usually the one which highest frequency (CCF) among all the regions/ passages you have available.

Does this make sense?

**Comment by arshah18** [comment]
Thank you for your reply. I completely agree with that.
There are variants whose _ccf_ is _zero_ in one passage but in consecutive passages have higher _ccf_ values. There can be one more situation where _variants_ in different _clusters_ have none _zero_ _ccf_ value in all the passages but overall average _ccf_ value is same. Do you think I should take the highest overall _average_ _ccf_ value as _clonal_? I have attached below a _synthetic data_, which _cluster_ do you think should I take as _clonal_ in following case?

Thank you!


mut_id | gene | R1.ccf | R2.ccf | R3.ccf | cluster
-- | -- | -- | -- | -- | --
1 | A1 | 0.6569 | 0.6508 | 0.7061 | 1
2 | A2 | 0.6569 | 0.6508 | 0.7061 | 1
3 | A3 | 0.6569 | 0.6508 | 0.7061 | 1
4 | A4 | 0.6569 | 0.6508 | 0.7061 | 1
5 | A5 | 0.6569 | 0.6508 | 0.7061 | 1
6 | A6 | 0.6569 | 0.6508 | 0.7061 | 1
7 | A7 | 0.6569 | 0.6508 | 0.7061 | 1
8 | A8 | 0.531 | 0.857 | 0.643 | 2
9 | A9 | 0.531 | 0.857 | 0.643 | 2
10 | A10 | 0.531 | 0.857 | 0.643 | 2
11 | A11 | 0.531 | 0.857 | 0.643 | 2
12 | A12 | 0.531 | 0.857 | 0.643 | 2
13 | A13 | 0.531 | 0.857 | 0.643 | 2
14 | A14 | 0.531 | 0.857 | 0.643 | 2
15 | A15 | 0.531 | 0.857 | 0.643 | 2
16 | A16 | 0.531 | 0.857 | 0.643 | 2
17 | A17 | 0 | 0.57 | 0.9759 | 3
18 | A18 | 0 | 0.57 | 0.9759 | 3
19 | A19 | 0 | 0.57 | 0.9759 | 3
20 | A20 | 0 | 0.57 | 0.9759 | 3
21 | A21 | 0 | 0.57 | 0.9759 | 3
22 | A22 | 0 | 0.57 | 0.9759 | 3
23 | A23 | 0 | 0.57 | 0.9759 | 3
24 | A24 | 0 | 0.57 | 0.9759 | 3
25 | A25 | 0 | 0.57 | 0.9759 | 3
26 | A26 | 0 | 0.57 | 0.9759 | 3
27 | A27 | 0 | 0.57 | 0.9759 | 3
28 | A28 | 0 | 0.57 | 0.9759 | 3
29 | A29 | 0 | 0.57 | 0.9759 | 3
30 | A30 | 0.948 | 0.895 | 0 | 4
31 | A31 | 0.948 | 0.895 | 0 | 4
32 | A32 | 0.948 | 0.895 | 0 | 4
33 | A33 | 0.948 | 0.895 | 0 | 4
34 | A34 | 0.948 | 0.895 | 0 | 4
35 | A35 | 0.948 | 0.895 | 0 | 4
36 | A36 | 0.948 | 0.895 | 0 | 4

**Comment by caravagn** [comment]
Honestly I don't think these CCF values make much sense. How are you simulating those?

**Comment by caravagn** [comment]
The weird thins is the ccf on r2 for cluster 2 being not the max. Otherwise that wild be the clonal cluster. 

Inviato da iPhone

**Comment by arshah18** [comment]
This is my subset of the original data:
I generate clusters using _Pyclone-vi_ with the following commands:
_$pyclone-vi fit -i inputFile.tsv -o outputResults.h5 -c 40 -d beta-binomial -r 10
$pyclone-vi write-results-file -i outputResults.h5 -o outputResultsCluster.tsv_


_inputFile.tsv_
mutation_id | sample_id | ref_counts | alt_counts | major_cn | minor_cn | normal_cn
-- | -- | -- | -- | -- | -- | --
1 | R1 | 92 | 0 | 2 | 1 | 2
2 | R1 | 56 | 75 | 2 | 1 | 2
3 | R1 | 56 | 28 | 2 | 1 | 2
4 | R1 | 92 | 0 | 2 | 1 | 2
5 | R1 | 105 | 98 | 2 | 1 | 2
6 | R1 | 92 | 0 | 2 | 1 | 2
7 | R1 | 92 | 0 | 2 | 1 | 2
8 | R1 | 83 | 99 | 2 | 1 | 2
9 | R1 | 92 | 0 | 2 | 1 | 2
10 | R1 | 40 | 4 | 2 | 1 | 2
11 | R1 | 38 | 40 | 2 | 1 | 2
12 | R1 | 28 | 23 | 2 | 1 | 2
13 | R1 | 28 | 24 | 2 | 1 | 2
14 | R1 | 92 | 0 | 2 | 1 | 2
15 | R1 | 92 | 0 | 2 | 1 | 2
16 | R1 | 68 | 60 | 2 | 1 | 2
17 | R1 | 92 | 0 | 2 | 1 | 2
18 | R2 | 36 | 37 | 2 | 1 | 2
19 | R2 | 92 | 0 | 2 | 1 | 2
20 | R2 | 34 | 22 | 2 | 1 | 2
21 | R2 | 92 | 0 | 2 | 1 | 2
22 | R2 | 52 | 51 | 2 | 1 | 2
23 | R2 | 92 | 0 | 2 | 1 | 2
24 | R2 | 92 | 0 | 2 | 1 | 2
25 | R2 | 33 | 30 | 2 | 1 | 2
26 | R2 | 92 | 0 | 2 | 1 | 2
27 | R2 | 29 | 27 | 2 | 1 | 2
28 | R2 | 42 | 44 | 2 | 1 | 2
29 | R2 | 14 | 13 | 2 | 1 | 2
30 | R2 | 43 | 34 | 2 | 1 | 2
31 | R2 | 92 | 0 | 2 | 1 | 2
32 | R2 | 28 | 35 | 2 | 1 | 2
33 | R2 | 26 | 18 | 2 | 1 | 2
34 | R3 | 42 | 4 | 2 | 1 | 2
35 | R3 | 92 | 0 | 2 | 1 | 2
36 | R3 | 67 | 85 | 2 | 1 | 2
37 | R3 | 40 | 54 | 2 | 1 | 2
38 | R3 | 92 | 0 | 2 | 1 | 2
39 | R3 | 92 | 0 | 2 | 1 | 2
40 | R3 | 32 | 39 | 2 | 1 | 2
41 | R3 | 6 | 13 | 2 | 1 | 2
42 | R3 | 92 | 0 | 2 | 1 | 2
43 | R3 | 92 | 0 | 2 | 1 | 2
44 | R3 | 83 | 87 | 2 | 1 | 2
45 | R3 | 92 | 0 | 2 | 1 | 2
46 | R3 | 92 | 0 | 2 | 1 | 2
47 | R3 | 92 | 0 | 2 | 1 | 2
48 | R3 | 92 | 0 | 2 | 1 | 2
49 | R3 | 92 | 0 | 2 | 1 | 2
50 | R3 | 92 | 0 | 2 | 1 | 2
51 | R3 | 92 | 0 | 2 | 1 | 2
52 | R3 | 92 | 0 | 2 | 1 | 2
53 | R3 | 92 | 0 | 2 | 1 | 2
54 | R3 | 64 | 49 | 2 | 1 | 2

**Comment by arshah18** [comment]
Ah, I see, I should have first gone through the the issues you have already answered [here](https://github.com/caravagnalab/revolver/issues?q=is%3Aissue+is%3Aclosed). Thanks for the detailed answers to most of the doubts I have, you have covered them [here](https://github.com/caravagnalab/revolver/issues?q=is%3Aissue+is%3Aclosed).

**Comment by caravagn** [comment]
Cool, no prob!

G
